### ISSUE TITLE
Log Analytics auto provisioning is deprecated

### ISSUE THREAD

**Issue by holmanjd** [Azure/terraform-azure-mdc-defender-plans-azure#92]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.6.9

### Module Version

2.0.0

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

module "mdc-defender-plans-azure" {
  source           = "Azure/mdc-defender-plans-azure/azure"
  version          = "2.0.0"
  enable_telemetry = false
  location         = var.location
  mdc_plans_list   = ["VirtualMachines"]
  subplans         = {"VirtualMachines":"P2"}
  providers        = {azurerm = azurerm.hub}
}

### tfvars variables values

variable "location" {
  description = "The Azure region for most Mission LZ resources. e.g. for government usgovvirginia"
  type        = string
  default     = "East US"
}

### Debug Output/Panic Output

 Error: updating auto-provisioning setting for Auto Provisioning Setting: (Name "default"): security.AutoProvisioningSettingsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Deprecated" Message="Log Analytics auto provisioning is deprecated and can no longer be enabled."
│
│   with module.mdc-defender-plans-azure.azurerm_security_center_auto_provisioning.auto_provisioning[0],
│   on .terraform\modules\mdc-defender-plans-azure\extensions_virtual_machines.tf line 61, in resource "azurerm_security_center_auto_provisioning" "auto_provisioning":        
│   61: resource "azurerm_security_center_auto_provisioning" "auto_provisioning" {
│

### Expected Behaviour

Deploy new AMA module instead of Log Analytics module

### Actual Behaviour

Module attempted to deploy Log Analytics module which was not allowed by the Azure APIs

**Comment by holmanjd** [comment]
Tested without the subplan being specified - same result (as expected).

**Comment by elibetito-microsoft** [comment]
Hi @holmanjd 

I wanted to let you know that the issue has been resolved, and the fix has been merged into the codebase.
[Remove deprecated Log Analytics agent #93](https://github.com/Azure/terraform-azure-mdc-defender-plans-azure/pull/93)

Please feel free to check if everything is working as expected. If you encounter any further issues or have additional questions, don’t hesitate to open a new issue or reach out to us.

Thank you for bringing this to our attention!
